# Data Analysis Project
## Offensive Tweets

First we start with Cross Validation using descrete classifying algorithms

In [152]:
import numpy as np
import pandas as pd

def your_code_here():
    return 0

df_train = pd.read_csv("train.csv")
df_test  = pd.read_csv("test.csv")
df_dev   = pd.read_csv("dev.csv")

df_train

                                                   text label category
0     @USER She should ask a few native Americans wh...   OFF      UNT
1     @USER @USER Go home you’re drunk!!! @USER #MAG...   OFF      TIN
2     Amazon is investigating Chinese employees who ...   NOT      NaN
3     @USER Someone should'veTaken" this piece of sh...   OFF      UNT
4     @USER @USER Obama wanted liberals &amp; illega...   NOT      NaN
...                                                 ...   ...      ...
1281  @USER @USER Mazzone has convinced him he can p...   NOT      NaN
1282  @USER Of course he does!!  #MAGA  for everyone...   NOT      NaN
1283  @USER It’s not bizarre. It’s smart business. H...   NOT      NaN
1284  @USER @USER @USER @USER @USER @USER @USER @USE...   NOT      NaN
1285  @USER I sure hope they have removed him from w...   NOT      NaN

[1286 rows x 3 columns]

In [153]:
from sklearn.feature_extraction.text import CountVectorizer
counter = CountVectorizer()
counter

CountVectorizer()

In [154]:
df_train_text = df_train['text']

X_train = counter.fit_transform(df_train_text)
analyze = counter.build_analyzer()
cols = counter.get_feature_names().copy()
cols

['00',
 '000',
 '08',
 '09',
 '10',
 '100',
 '1000',
 '10000',
 '1000x',
 '100b',
 '10kids',
 '10th',
 '11',
 '11th',
 '12',
 '13',
 '14',
 '15',
 '150',
 '1776',
 '17yrs',
 '18',
 '180',
 '19',
 '1917',
 '1968',
 '1978',
 '1986',
 '1989',
 '1991',
 '19th',
 '1m',
 '1million',
 '1st',
 '20',
 '2000',
 '2005',
 '2015',
 '2016',
 '2017',
 '2018',
 '2020',
 '20seconds',
 '21k',
 '21st',
 '22',
 '23',
 '24',
 '25',
 '250',
 '25m',
 '299',
 '2a',
 '2nd',
 '2u',
 '30',
 '300',
 '311',
 '325',
 '35',
 '36',
 '3m',
 '3rd',
 '40',
 '400',
 '40t',
 '45',
 '474',
 '48',
 '50',
 '500',
 '51',
 '55',
 '56',
 '5th',
 '63',
 '64m',
 '75',
 '7k',
 '84',
 '85',
 '8chan',
 '90s',
 '95',
 '99',
 '____',
 '_against',
 'aaa',
 'ab',
 'aback',
 'abbott',
 'abducted',
 'abiding',
 'ability',
 'able',
 'ableg',
 'aborting',
 'abortion',
 'about',
 'above',
 'absence',
 'absolute',
 'absolutely',
 'absurd',
 'abuse',
 'abused',
 'abusers',
 'abusive',
 'abysmal',
 'abyss',
 'academy',
 'accept',
 'access',
 'accessories',
 'accompanies',
 'accomplish',
 'accordingly',
 'account',
 'accountability',
 'accountable',
 'accounts',
 'accusations',
 'accuse',
 'accused',
 'accuser',
 'accusers',
 'accuses',
 'accusing',
 'acknowledge',
 'across',
 'act',
 'acting',
 'action',
 'actions',
 'active',
 'actively',
 'activist',
 'activists',
 'activities',
 'actor',
 'actress',
 'acts',
 'actual',
 'actually',
 'actualy',
 'ad',
 'add',
 'added',
 'addiction',
 'address',
 'addresses',
 'administration',
 'admiration',
 'admire',
 'admit',
 'admitted',
 'admitting',
 'adopt',
 'adoptive',
 'adorable',
 'adult',
 'adults',
 'adventures',
 'advice',
 'advisement',
 'advisory',
 'advocates',
 'aesir',
 'affordable',
 'afforded',
 'afraid',
 'africa',
 'african',
 'africans',
 'after',
 'aftermath',
 'again',
 'against',
 'age',
 'agenda',
 'agent',
 'agentofchaurch',
 'aggressive',
 'agholor',
 'agitated',
 'ago',
 'agree',
 'agreeing',
 'agreement',
 'agt',
 'agtresults',
 'ah',
 'aha',
 'ahead',
 'ai',
 'aid',
 'aims',
 'ain',
 'aint',
 'air',
 'airforce',
 'ajsjjsjdkkdjdk',
 'aka',
 'al',
 'ala',
 'alarm',
 'alaska',
 'albertpike1871',
 'album',
 'albums',
 'alcatraz',
 'alert',
 'alex',
 'algorithm',
 'alien',
 'alike',
 'alinskyite',
 'alive',
 'all',
 'allegation',
 'allegations',
 'alleged',
 'alleslev',
 'alliance',
 'allies',
 'alloutpolitics',
 'allow',
 'allowed',
 'allows',
 'almost',
 'alone',
 'along',
 'already',
 'alright',
 'also',
 'alt',
 'alternativefacts',
 'although',
 'always',
 'alyssa',
 'am',
 'amateur',
 'amazing',
 'amazingly',
 'amazon',
 'ambition',
 'amen',
 'amends',
 'america',
 'americafirst',
 'american',
 'americans',
 'americas',
 'ammunition',
 'amnesia',
 'among',
 'amongst',
 'amount',
 'amp',
 'an',
 'anarchist',
 'ancient',
 'and',
 'angel',
 'angela',
 'anger',
 'angling',
 'angry',
 'animal',
 'animals',
 'anime',
 'anita',
 'anna',
 'announced',
 'announcements',
 'annoyance',
 'anonymous',
 'another',
 'ans',
 'answer',
 'answers',
 'anthony',
 'anti',
 'antiamerican',
 'antics',
 'antideutsch',
 'antifa',
 'anupama',
 'any',
 'anymore',
 'anyone',
 'anything',
 'anytime',
 'anyway',
 'anyways',
 'anywhere',
 'ap',
 'apart',
 'apologetic',
 'apologized',
 'apology',
 'apparently',
 'appears',
 'applauded',
 'application',
 'applies',
 'apply',
 'appointed',
 'appointment',
 'appreciate',
 'approach',
 'appropriate',
 'approved',
 'april',
 'apt',
 'arc',
 'archived',
 'are',
 'aren',
 'argument',
 'arguments',
 'arm',
 'armed',
 'arms',
 'army',
 'arnold',
 'around',
 'arrest',
 'arrests',
 'arrive',
 'art',
 'article',
 'artist',
 'as',
 'asap',
 'ash',
 'ask',
 'asked',
 'asking',
 'asmr',
 'aspect',
 'ass',
 'assange',
 'assassin',
 'assassinating',
 'assassination',
 'assault',
 'assaulted',
 'assaulting',
 'assertions',
 'asset',
 'assholes',
 'associate',
 'assume',
 'assuming',
 'assumption',
 'asylum',
 'at',
 'ate',
 'atempted',
 'atf',
 'athens',
 'atmosphere',
 'attack',
 'attacked',
 'attacking',
 'attacks',
 'attempted',
 'attempting',
 'attempts',
 'attendees',
 'attending',
 'attention',
 'attitude',
 'attkisson',
 'attlee',
 'attorneys',
 'aubree',
 'audience',
 'aunt',
 'aurora',
 'aust',
 'austerity',
 'australia',
 'australian',
 'authoritarian',
 'authorized',
 'auto',
 'available',
 'average',
 'avg',
 'avoids',
 'awake',
 'awakened',
 'awakening',
 'aware',
 'away',
 'awe',
 'awesome',
 'awesomee',
 'awful',
 'awww',
 'axes',
 'axis',
 'b4',
 'b4u',
 'baby',
 'babysitting',
 'back',
 'backed',
 'background',
 'backgrounds',
 'backing',
 'backs',
 'backwood',
 'bad',
 'bags',
 'baiters',
 'balaam',
 'balance',
 'ball',
 'ballot',
 'balls',
 'ban',
 'band',
 'bangle',
 'bank',
 'banks',
 'banned',
 'banner',
 'banning',
 'bar',
 'barred',
 'base',
 'baseball',
 'based',
 'bash',
 'bashing',
 'basically',
 'basis',
 'basket',
 'bastards',
 'bat',
 'batch',
 'batsht',
 'battering',
 'batting',
 'battle',
 'bay',
 'bbc',
 'bc',
 'bco',
 'be',
 'beaboutit',
 'beacon',
 'bear',
 'bears',
 'beast',
 'beat',
 'beatdown',
 'beating',
 'beautiful',
 'beaware',
 'becaus',
 'because',
 'become',
 'becoming',
 'bed',
 'been',
 'beer',
 'before',
 'begin',
 'beginning',
 'begone',
 'behalf',
 'behar',
 'behaved',
 'behaves',
 'behaving',
 'behavior',
 'behind',
 'being',
 'believable',
 'believe',
 'believed',
 'believes',
 'believing',
 'bell',
 'belly',
 'belong',
 'ben',
 'bench',
 'beneathhumanity',
 'benefit',
 'benefits',
 'benfica',
 'bernie',
 'bernier',
 'besides',
 'best',
 'bestfriend',
 'bet',
 'beto',
 'betonotfortexas',
 'betrayal',
 'betrayed',
 'better',
 'between',
 'beyond',
 'bff',
 'bhakt',
 'biased',
 'bible',
 'bickle',
 'biden',
 'big',
 'biggest',
 'bigoted',
 'bill',
 'billion',
 'billions',
 'bills',
 'billy',
 'bingbing',
 'binnedboris',
 'bird',
 'birdemic',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bitch',
 'bitches',
 'bites',
 'bitten',
 'bitter',
 'bizarre',
 'bjp',
 'black',
 'blacks',
 'blame',
 'blamed',
 'blaming',
 'blasey',
 'blatant',
 'blender',
 'bless',
 'blind',
 'blindly',
 'blm',
 'bloated',
 'blobs',
 'block',
 'blocked',
 'blocklists',
 'blocktogether',
 'blood',
 'bloody',
 'bloomberg',
 'blow',
 'blowing',
 'blown',
 'blue',
 'bnf',
 'board',
 'boarders',
 'boards',
 'bobby',
 'body',
 'boggles',
 'boi',
 'bold',
 'bomb',
 'boner',
 'bono',
 'boo',
 'book',
 'books',
 'boom',
 'boomingeconomy',
 'booom',
 'boost',
 'booted',
 'boots',
 'border',
 'borders',
 'born',
 'borrow',
 'borrowed',
 'boss',
 'bosses',
 'bot',
 'both',
 'bottom',
 'bought',
 'bounce',
 'bout',
 'bowel',
 'boxer',
 'boy',
 'boycott',
 'boycottnfl',
 'boycottnike',
 'boys',
 'bracelets',
 'brady',
 'brain',
 'brainless',
 'brains',
 'brainwashed',
 'branch',
 'brass',
 'brave',
 'bravery',
 'bray',
 'brazil',
 'brazilian',
 'brazilians',
 'break',
 'breakdown',
 'breaked',
 'breaking',
 'breaks',
 'breath',
 'breed',
 'breibart',
 'breitbart',
 'brennan',
 'brett',
 'brexit',
 'brexitbritain',
 'brexitmeansbrexit',
 'brexitshambles',
 'brian',
 'bridge',
 'bridges',
 'brief',
 'bright',
 'brigitte',
 'brilliance',
 'brilliancy',
 'bring',
 'bringing',
 'britain',
 'british',
 'brits',
 'bro',
 'broadcast',
 'broderick',
 'broke',
 'broken',
 'brothel',
 'brother',
 'brothers',
 'brought',
 'brown',
 'browns',
 'bruh',
 'brutalist',
 'brutality',
 'bs',
 'bts',
 'btw',
 'bubbler',
 'buddies',
 'buddy',
 'budget',
 'buh',
 'buhbye',
 'build',
 'building',
 'built',
 'bulb',
 'bull',
 'bullshit',
 'bullshitting',
 'bully',
 'bullying',
 'bump',
 'bumper',
 'bunch',
 'bunga',
 'bunk',
 'bunker',
 'burn',
 'burnol',
 'burnt',
 'burrard',
 'burt',
 'burying',
 'business',
 'busted',
 'busy',
 'but',
 'butt',
 'butthurt',
 'buy',
 'buying',
 'buys',
 'by',
 'bystanders',
 'ca',
 'cabal',
 'cabbage',
 'caged',
 'cages',
 'cake',
 'cal',
 'caliber',
 'california',
 'call',
 'called',
 'calling',
 'callthevotealready',
 'calm',
 'cam',
 'cambridge',
 'came',
 'camera',
 'camila',
 'campaign',
 'campaigned',
 'campers',
 'can',
 'canada',
 'canadian',
 'canadians',
 'cancer',
 'candace',
 'candidate',
 'candidates',
 'candy',
 'cannot',
 'cant',
 'cap',
 'capablities',
 'capacity',
 'capital',
 'capitalism',
 'carbon',
 'card',
 'cardi',
 'care',
 'career',
 'cares',
 'caribbean',
 'caring',
 'carla',
 'carmen',
 'carnival',
 'carried',
 'carry',
 'cartel',
 'carter',
 'cartoon',
 'cartoons',
 'case',
 'cases',
 'casey',
 'cash',
 'casters',
 'cat',
 'catch',
 'catches',
 'catching',
 'categorizes',
 'cater',
 'catfight',
 'catholic',
 'catholics',
 'cats',
 'caught',
 'causation',
 'cause',
 'caused',
 'causes',
 'cbc',
 'cbs',
 'ccot',
 'cda',
 'cdnhist',
 'cdnpoli',
 'celeb',
 'celebrate',
 'celebrated',
 'celebs',
 'cells',
 'censored',
 'censoring',
 'center',
 'centralize',
 'centrist',
 'centuries',
 'century',
 'ceo',
 'certainly',
 'certifiable',
 'chains',
 'challenge',
 'challenges',
 'chance',
 'chandigarh',
 'change',
 'changed',
 'changer',
 'changes',
 'changing',
 'character',
 'characterizations',
 'charge',
 'charges',
 'charlottesville',
 'charts',
 'chasing',
 'cheap',
 'cheat',
 'cheating',
 'check',
 'chelsea',
 'chequers',
 'chess',
 'chest',
 'chicago',
 'chicken',
 'chico',
 'chihuahua',
 'child',
 'childish',
 'children',
 'chill',
 'chiming',
 'china',
 'chinese',
 'chips',
 'chlorine',
 'chocker',
 'choice',
 'choices',
 'choose',
 'chris',
 'christ',
 'christian',
 'christians',
 'christina',
 'christine',
 'christineblaseyford',
 'christopher',
 'chuck',
 'chucky',
 'chum',
 'circulated',
 'circulation',
 'circumstance',
 'circus',
 'cities',
 'citizen',
 'citizens',
 'citizenship',
 'city',
 'civically',
 'civil',
 'cj',
 'claim',
 'claiming',
 'claims',
 'clarence',
 'clarencethomas',
 'clarkson',
 'class',
 'classes',
 'classical',
 'claudia',
 'cleaned',
 'cleaning',
 'clear',
 'clearly',
 'clever',
 'cliffs',
 'climate',
 'clinton',
 'clintoncrimes',
 'clintonfoundation',
 'close',
 'closernation',
 'closest',
 'closet',
 'closing',
 'clown',
 'clue',
 'clueless',
 'cnn',
 'co',
 'coalition',
 'coast',
 'cock',
 'cocks',
 'code',
 'coffin',
 'cognitive',
 'coin',
 'coincidence',
 'collected',
 'collection',
 'collective',
 'college',
 'colleges',
 'collins',
 'collusion',
 'colon',
 'colonialism',
 'color',
 'colossal',
 'coma',
 'combat',
 'combos',
 'come',
 'comedians',
 'comes',
 'comforted',
 'comic',
 'coming',
 'commandments',
 'comment',
 'comments',
 'commieclowns',
 'commiessuck',
 'committed',
 'committee',
 'common',
 'communism',
 'communist',
 'communistic',
 'communists',
 'community',
 'company',
 'comparison',
 'competence',
 'competent',
 'competing',
 'competitive',
 'complaining',
 'complains',
 'complaint',
 'complete',
 'completely',
 'complicit',
 'compose',
 'comprehend',
 'comprehension',
 'comprised',
 'compromising',
 'comrade',
 'con',
 'concealed',
 'concentration',
 'concept',
 'concern',
 'concerned',
 'concerns',
 'conclusions',
 'condemn',
 'condemnations',
 'condemning',
 'condition',
 'conditioning',
 'conditions',
 'conducted',
 'conf',
 'confederacy',
 'conference',
 'confess',
 'confirm',
 'confirmation',
 'confirmbrettkavanaughnow',
 'confirmcoachk',
 'confirmed',
 'confirmkavanaugh',
 'confiscated',
 'conflating',
 'conflict',
 'confronted',
 'confronting',
 'confused',
 'confusing',
 'congratulate',
 'congratulations',
 'congress',
 'connect',
 'connected',
 'connection',
 'connections',
 'connor',
 'connors',
 'cons',
 'conscience',
 'conservatards',
 'conservative',
 'conservatives',
 'conservatives_',
 'consider',
 ...]

In [155]:
X_test = counter.transform(df_test['text'])
(X_train,X_test)

(<1286x4793 sparse matrix of type '<class 'numpy.int64'>'
 	with 22802 stored elements in Compressed Sparse Row format>,
 <1293x4793 sparse matrix of type '<class 'numpy.int64'>'
 	with 20265 stored elements in Compressed Sparse Row format>)

## Transform Vectorized Text Dataframe into tfidf matrix

In [156]:
from sklearn.feature_extraction.text import TfidfTransformer as tf
transformer = tf(smooth_idf=False)
transformer

TfidfTransformer(smooth_idf=False)

In [157]:
tfidf = transformer.fit_transform(X_train.toarray())
tfidf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [158]:
from sklearn.feature_extraction.text import TfidfVectorizer as tfv
vectorizer = tfv()
X_train_pp = vectorizer.fit_transform(df_train_text)
X_test_pp  = vectorizer.transform(df_test['text'])
df_train_pp = pd.DataFrame(data=X_train_pp.toarray(),columns = cols)
df_test_pp = pd.DataFrame(data=X_test_pp.toarray(), columns = cols)

In [165]:
train = pd.concat([df_train_pp,df_train[['label','category']]],1)
test  = pd.concat([df_test_pp, df_dev[['label','category']]])

In [166]:
train.to_csv("train_pp.csv")
test.to_csv("test_pp.csv")

In [168]:
train.replace(['NOT', 'OFF', 'NaN', 'UNT', 'TIN'], [0, 1, 0, 1, 2])
test.replace(['NOT', 'OFF', 'NaN', 'UNT', 'TIN'], [0, 1, 0, 1, 2])

,00,000,08,09,10,100,1000,10000,1000x,100b,...,zero,zionists,zipcode,zones,žižek,𝓭𝔂𝓼𝓹𝓱𝓸𝓻𝓲𝓪,𝙼𝚌𝙿𝙾𝚄𝚃𝚂𝙵𝚊𝚌𝚎,𝙿𝚎𝚝𝚊𝚕𝚜,label,category
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
10310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
10311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
10312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
10313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0

In [169]:
test

,00,000,08,09,10,100,1000,10000,1000x,100b,...,zero,zionists,zipcode,zones,žižek,𝓭𝔂𝓼𝓹𝓱𝓸𝓻𝓲𝓪,𝙼𝚌𝙿𝙾𝚄𝚃𝚂𝙵𝚊𝚌𝚎,𝙿𝚎𝚝𝚊𝚕𝚜,label,category
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NOT,NaN
10310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OFF,TIN
10311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NOT,NaN
10312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OFF,TIN
10313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OFF,UNT

In [170]:
train

,00,000,08,09,10,100,1000,10000,1000x,100b,...,zero,zionists,zipcode,zones,žižek,𝓭𝔂𝓼𝓹𝓱𝓸𝓻𝓲𝓪,𝙼𝚌𝙿𝙾𝚄𝚃𝚂𝙵𝚊𝚌𝚎,𝙿𝚎𝚝𝚊𝚕𝚜,label,category
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OFF,UNT
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OFF,TIN
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NOT,NaN
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OFF,UNT
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NOT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1281,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NOT,NaN
1282,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NOT,NaN
1283,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NOT,NaN
1284,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NOT,NaN
1285,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NOT,NaN