In [110]:
import pandas as pd
import numpy  as np
import matplotlib.pyplot as plt
from sklearn import svm
import random
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture

test_size = 1000

In [111]:
co_p = np.random.normal(1,1,size=(1000+test_size,2))
co_n = np.random.normal(1,1,size=(1000+test_size,2))

X_p = pd.DataFrame(co_p,columns=['x0','x1'])
X_n = pd.DataFrame(co_n,columns=['x0','x1'])

In [120]:
X_p

            x0        x1
0     0.380227  1.791249
1     2.134794  2.252780
2     1.103683  1.056895
3    -0.134885  2.444780
4    -0.292226 -0.824050
...        ...       ...
1995  1.081198  2.095480
1996  2.141481  1.572412
1997  2.009426  1.497228
1998  0.056259  2.237747
1999  1.438126  0.577751

[2000 rows x 2 columns]

In [121]:
X_n

            x0        x1
0     0.461192  0.847919
1     0.344490  1.900830
2    -0.772668  1.474375
3     0.111454  2.037419
4     1.062457  1.926822
...        ...       ...
1995  0.959253  1.987059
1996 -1.233827  0.004926
1997  2.823265  3.019866
1998  1.158924  2.574512
1999  2.763948 -0.288612

[2000 rows x 2 columns]

In [116]:
mean = 0
for i in range(0,20):
    
    # Flipping Labels
    y_p = np.full(1000+test_size,1)
    y_n = np.full(1000+test_size,-1)
    for j in range(0,len(y_p)):
        y_p[j] = 1 if (random.randint(0,100)>35) else -1
    for j in range(0,len(y_n)):
        y_n[j] = -1 if (random.randint(0,100)>20) else 1
        
    # Constructing Dataframe
    df_p = pd.concat([X_p,pd.DataFrame(y_p,columns=['y'])],1)
    df_n = pd.concat([X_n,pd.DataFrame(y_n,columns=['y'])],1)
    df  = pd.concat([df_p,df_n],0)
    
    # Running SVM
    clf_a = svm.SVC(kernel='rbf', C=1, gamma=0.01)
    clf_a.fit(df[['x0','x1']][:1000],df['y'][:1000])
    score = clf_a.score(df[['x0','x1']][1000:],df['y'][1000:])
    
    # Report Scores
    print(score)
    mean +=score
    
mean = mean/20
mean

0.34933333333333333
0.3586666666666667
0.348
0.365
0.36233333333333334
0.3506666666666667
0.347
0.3443333333333333
0.346
0.3506666666666667
0.3476666666666667
0.3446666666666667
0.35633333333333334
0.36033333333333334
0.3566666666666667
0.3596666666666667
0.34833333333333333
0.36733333333333335
0.3556666666666667
0.3516666666666667

0.3535166666666667

In [117]:
mean = 0
for i in range(0,20):
    
    # Flipping Labels
    y_p = np.full(1000+test_size,1)
    y_n = np.full(1000+test_size,-1)
    for j in range(0,len(y_p)):
        y_p[j] = 1 if (random.randint(0,100)>35) else -1
    for j in range(0,len(y_n)):
        y_n[j] = -1 if (random.randint(0,100)>20) else 1
        
    # Constructing Dataframe
    df_p = pd.concat([X_p,pd.DataFrame(y_p,columns=['y'])],1)
    df_n = pd.concat([X_n,pd.DataFrame(y_n,columns=['y'])],1)
    df  = pd.concat([df_p,df_n],0)
    
    cleaner = KNeighborsClassifier(n_neighbors=100).fit(df[['x0','x1']],df['y'])
    df['y'] = cleaner.predict(df[['x0','x1']])
    
    # Running SVM
    clf_a = svm.SVC(kernel='rbf', C=1, gamma=0.01)
    clf_a.fit(df[['x0','x1']][:1000],df['y'][:1000])
    score = clf_a.score(df[['x0','x1']][1000:],df['y'][1000:])
    
    # Report Scores
    print(score)
    mean +=score
    
mean = mean/20
mean

0.932
0.967
0.904
0.9713333333333334
0.9776666666666667
0.872
0.9526666666666667
0.9273333333333333
0.9513333333333334
0.933
0.9833333333333333
0.9366666666666666
0.9533333333333334
0.9783333333333334
0.9566666666666667
0.8813333333333333
0.9413333333333334
0.9543333333333334
0.964
0.9453333333333334

0.9441499999999999

In [118]:
mean = 0
for i in range(0,20):
    
    # Flipping Labels
    y_p = np.full(1000+test_size,1)
    y_n = np.full(1000+test_size,-1)
    for j in range(0,len(y_p)):
        y_p[j] = 1 if (random.randint(0,100)>35) else -1
    for j in range(0,len(y_n)):
        y_n[j] = -1 if (random.randint(0,100)>20) else 1
        
    # Constructing Dataframe
    df_p = pd.concat([X_p,pd.DataFrame(y_p,columns=['y'])],1)
    df_n = pd.concat([X_n,pd.DataFrame(y_n,columns=['y'])],1)
    df  = pd.concat([df_p,df_n],0)
    
    df['y'] = KMeans(n_clusters=2, random_state=0).fit_predict(df[['x0','x1']])
    
    # Running SVM
    clf_a = svm.SVC(kernel='rbf', C=1, gamma=0.01)
    clf_a.fit(df[['x0','x1']][:1000],df['y'][:1000])
    score = clf_a.score(df[['x0','x1']][1000:],df['y'][1000:])
    
    # Report Scores
    print(score)
    mean +=score
    
mean = mean/20
mean

0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333
0.9923333333333333

0.9923333333333332

In [119]:
mean = 0
for i in range(0,20):
    
    # Flipping Labels
    y_p = np.full(1000+test_size,1)
    y_n = np.full(1000+test_size,-1)
    for j in range(0,len(y_p)):
        y_p[j] = 1 if (random.randint(0,100)>35) else -1
    for j in range(0,len(y_n)):
        y_n[j] = -1 if (random.randint(0,100)>20) else 1
        
    # Constructing Dataframe
    df_p = pd.concat([X_p,pd.DataFrame(y_p,columns=['y'])],1)
    df_n = pd.concat([X_n,pd.DataFrame(y_n,columns=['y'])],1)
    df  = pd.concat([df_p,df_n],0)
    
    df['y'] = GaussianMixture(n_components=2, covariance_type='full').fit_predict(df[['x0','x1']])
    
    # Running SVM
    clf_a = svm.SVC(kernel='rbf', C=1, gamma=0.01)
    clf_a.fit(df[['x0','x1']][:1000],df['y'][:1000])
    score = clf_a.score(df[['x0','x1']][1000:],df['y'][1000:])
    
    # Report Scores
    print(score)
    mean +=score
    
mean = mean/20
mean

0.9936666666666667
0.9896666666666667
0.9936666666666667
0.9876666666666667
0.9893333333333333
0.9896666666666667
0.9753333333333334
0.9906666666666667
0.9963333333333333
0.992
0.9916666666666667
0.9843333333333333
0.9903333333333333
0.9906666666666667
0.9776666666666667
0.9886666666666667
0.995
0.989
0.979
0.9863333333333333

0.9885333333333334